@base_url=http://localhost:3000
@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFlZjViMzhkLTAyNTktNGQ0ZC04ZDViLTE5NDVmZTA2OTI2MSIsImVtYWlsIjoibWF0aGV1cy5tb3RhQGdtYWlsLmNvbSIsIm5hbWUiOiJNYXRoZXVzIE1vdGEiLCJpYXQiOjE3MjM2MDgzNjV9.l2MWgRvdQTfdNVFMFXJCHlErf_lhNZOPU1uGK7LmoVk

###

GET {{base_url}}

###

POST {{base_url}}/users
Content-Type: application/json

{
    "name": "Matheus Lopes",
    "email": "matheus.lopes@gmail.com",
    "password": "123123"
}

###

POST {{base_url}}/users/signin
Content-Type: application/json

{
    "email": "matheus.mota@gmail.com",
    "password": "123123"
}

###

DELETE {{base_url}}/users/signout
Cookie: access_token={{access_token}}
Content-Type: application/json

###

GET {{base_url}}/users
Cookie: access_token={{access_token}}
Content-Type: application/json